export const bgImages = [
  "https://images.unsplash.com/photo-1598153346810-860daa814c4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aGFycnklMjBwb3R0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1547756536-cde3673fa2e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aGFycnklMjBwb3R0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1583997052301-0042b33fc598?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8aGFycnklMjBwb3R0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1548630826-2ec01a41f48f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8aGFycnklMjBwb3R0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1618944847828-82e943c3bdb7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8aGFycnklMjBwb3R0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1618944913480-b67ee16d7b77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8aGFycnklMjBwb3R0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1571936804022-90d128047136?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1533462506003-13c20d204b58?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGhvZ3dhcnRzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1626914535205-8e4e3bf36793?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjN8fGhvZ3dhcnRzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1619622338668-484d0f2e1c3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njd8fGhvZ3dhcnRzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1539103377911-4909a1eae382?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1610466024868-910c6e7e8929?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1632266484284-a11d9e3a460a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1575887339850-1acc9d8daf3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1618945034861-7e61e0326e74?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njl8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "https://images.unsplash.com/photo-1498676077434-7540603d2dda?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODh8fGhhcnJ5JTIwcG90dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
];

export const housesInfo = [
  {
    houseName: "Slytherin",
    houseCrest: "./assets/crest-slytherin.png",
    count: 0,
  },
  {
    houseName: "Gryffindor",
    houseCrest: "./assets/crest-gryffindor.png",
    count: 0,
  },
  {
    houseName: "Ravenclaw",
    houseCrest: "./assets/crest-ravenclaw.png",
    count: 0,
  },
  {
    houseName: "Hufflepuff",
    houseCrest: "./assets/crest-hufflepuff.png",
    count: 0,
  },
];

export const allQuestions = [
  /* {
    question: "Which word below describes you best?",
    slytherinOption: "cunning",
    gryffindorOption: "brave",
    ravenclawOption: "clever",
    hufflepuffOption: "friendly",
    weight: 3,
  },
  {
    question: "What's your favorite animal?",
    slytherinOption: "snake",
    gryffindorOption: "lion",
    ravenclawOption: "raven",
    hufflepuffOption: "badger",
    weight: 2,
  },
  {
    question: "What's your favorite color?",
    slytherinOption: "green",
    gryffindorOption: "scarlet",
    ravenclawOption: "blue",
    hufflepuffOption: "yellow",
    weight: 1,
  },
  {
    question: "What do you find the most interesting?",
    slytherinOption: "hexes",
    gryffindorOption: "broom flying",
    ravenclawOption: "transfiguration",
    hufflepuffOption: "care of magical creatures",
    weight: 2,
  },
  {
    question: "Which famous Hogwarts alumnus/alumna would you like to meet?",
    slytherinOption: "Tom Riddle",
    gryffindorOption: "Albus Dumbledore",
    ravenclawOption: "Garrick Olivander",
    hufflepuffOption: "Cedric Diggory",
    weight: 1,
  },
  {
    question: "What's your favorite movie genre?",
    slytherinOption: "crime",
    gryffindorOption: "action",
    ravenclawOption: "documentary",
    hufflepuffOption: "comedy",
    weight: 2,
  },
  {
    question: "How do you see yourself in the Mirror of Erised?",
    slytherinOption: "with riches",
    gryffindorOption: "on an adventure",
    ravenclawOption: "with a book",
    hufflepuffOption: "with friends & family",
    weight: 3,
  },
  {
    question: "Of these four, which muggle profession would you choose?",
    slytherinOption: "salesperson",
    gryffindorOption: "firefighter",
    ravenclawOption: "researcher",
    hufflepuffOption: "caregiver",
    weight: 3,
  },
  {
    question: "What is at the core of your wand?",
    slytherinOption: "dragon heartstring",
    gryffindorOption: "phoenix feather",
    ravenclawOption: "veela hair",
    hufflepuffOption: "unicorn hair",
    weight: 2,
  },
  {
    question: "What part of Hogwarts are you most eager to explore?",
    slytherinOption: "the forbidden forest",
    gryffindorOption: "the room of requirement",
    ravenclawOption: "the library",
    hufflepuffOption: "the kitchen",
    weight: 2,
  },
  {
    question: "Which is your favorite Dumbledore quote?",
    slytherinOption:
      '"It matters not what someone is born, but what they grow to be."',
    gryffindorOption: '"It does not do to dwell on dreams and forget to live."',
    ravenclawOption:
      '"Words are, in my not-so-humble opinion, our most inexhaustible source of magic."',
    hufflepuffOption:
      '"Pity the living. And above all those who live without love."',
    weight: 3,
  },
  {
    question: "What type of Zodiac sign do you have?",
    slytherinOption: "fire",
    gryffindorOption: "earth",
    ravenclawOption: "air",
    hufflepuffOption: "water",
    weight: 1,
  },
  {
    question: "How would others describe you?",
    slytherinOption: "ambitious",
    gryffindorOption: "honorable",
    ravenclawOption: "curious",
    hufflepuffOption: "humble",
    weight: 2,
  },
  {
    question: "What would you rather be?",
    slytherinOption: "praised",
    gryffindorOption: "respected",
    ravenclawOption: "admired",
    hufflepuffOption: "trusted",
    weight: 3,
  },
  {
    question:
      "You encounter a troll on a bridge you want to cross; how do you deal with it?",
    slytherinOption: "kill it",
    gryffindorOption: "fight it fairly",
    ravenclawOption: "trick it",
    hufflepuffOption: "negotiate with it to let you pass",
    weight: 2,
  },
  {
    question: "Which leisure activity is most appealing to you?",
    slytherinOption: "improving myself",
    gryffindorOption: "trying something new",
    ravenclawOption: "reading",
    hufflepuffOption: "volunteering",
    weight: 2,
  },
  {
    question: "Which animal would you rather have as a pet?",
    slytherinOption: "lizard",
    gryffindorOption: "dog",
    ravenclawOption: "cat",
    hufflepuffOption: "bunny",
    weight: 1,
  },
  {
    question:
      "If you could make a potion that would guarantee you one thing, what would it be?",
    slytherinOption: "fame",
    gryffindorOption: "respect",
    ravenclawOption: "wisdom",
    hufflepuffOption: "love",
    weight: 1,
  }, */
  {
    question:
      "You find a bag with 10,000 galleons in it; what do you do with it?",
    slytherinOption: "Keep it & tell no one",
    gryffindorOption: "Go to the police with it",
    ravenclawOption: "Keep it & make a strategic investment",
    hufflepuffOption: "Try to find the owner",
    weight: 3,
  },
  {
    question: "Which house do you hope to be in?",
    slytherinOption: "slytherin",
    gryffindorOption: "gryffindor",
    ravenclawOption: "ravenclaw",
    hufflepuffOption: "hufflepuff",
    weight: 8,
  },
];
